import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSideProviders from "@/components/providers/ClientSideProviders";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className="flex flex-col gap-8 pt-4 h-dvh overflow-y-scroll
"
      >
        <ThemeProvider>
          <ClientSideProviders>{children}</ClientSideProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
